INSERT INTO filmes.Pais (Nome_Pais) VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo (Congo-Brazzaville)'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Democratic Republic of the Congo'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Eswatini'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar (formerly Burma)'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Korea'),
('North Macedonia (formerly Macedonia)'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Palestine State'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Sweden'),
('Switzerland'),
('Syria'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States of America'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City (Holy See)'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');

INSERT INTO filmes.Genero_Pessoa (Nome_Genero_Pessoa) VALUES
('Feminino'),
('Masculino'),
('Outro');

INSERT INTO filmes.Genero_Filme (Nome_Genero_Filme) VALUES
('Thriller');
INSERT INTO filmes.Genero_Filme (Nome_Genero_Filme) VALUES
('Ação'),
('Aventura'),
('Animação'),
('Biografia'),
('Comédia'),
('Crime'),
('Documentário'),
('Drama'),
('Família'),
('Fantasia'),
('História'),
('Terror'),
('Musical'),
('Mistério'),
('Romance'),
('Ficção Científica'),
('Esporte'),
('Suspense'),
('Guerra'),
('Faroeste'),
('Aventura Fantástica'),
('Comédia Romântica'),
('Anime'),
('Noir'),
('Cyberpunk'),
('Steampunk'),
('Épico'),
('Espionagem'),
('Super-herói'),
('Distopia'),
('Utopia'),
('Surrealismo'),
('Zumbi'),
('Slasher'),
('Gótico'),
('Vampiro'),
('Sobrenatural'),
('Paródia'),
('Thriller');

INSERT INTO filmes.Plataforma (Nome_Plataforma, Descricao) VALUES
('Netflix', 'Plataforma de streaming criada em 1997, oferece uma vasta biblioteca de filmes, séries e documentários.'),
('Amazon Prime Video', 'Serviço de streaming da Amazon lançado em 2006, conhecido por suas produções originais e ampla seleção de conteúdo.'),
('YouTube', 'Plataforma de compartilhamento de vídeos criada em 2005, permite upload, visualização e compartilhamento de vídeos.'),
('Disney+', 'Plataforma de streaming da Disney lançada em 2019, oferece conteúdo da Disney, Pixar, Marvel, Star Wars e National Geographic.'),
('HBO Max', 'Serviço de streaming da WarnerMedia lançado em 2020, oferece filmes, séries e conteúdo exclusivo da HBO.'),
('Apple TV+', 'Serviço de streaming da Apple lançado em 2019, conhecido por suas produções originais de alta qualidade.'),
('Hulu', 'Serviço de streaming lançado em 2007, focado em séries de TV, filmes e conteúdo original.'),
('Paramount+', 'Plataforma de streaming da ViacomCBS lançada em 2021, oferece filmes, séries e conteúdo esportivo ao vivo.'),
('Peacock', 'Serviço de streaming da NBCUniversal lançado em 2020, oferece uma variedade de filmes, séries e programas de TV.'),
('Crunchyroll', 'Plataforma de streaming focada em anime, lançada em 2006, oferece uma ampla seleção de séries e filmes de anime.'),
('Funimation', 'Serviço de streaming especializado em anime, lançado em 1994, oferece dublagens e legendas em vários idiomas.');

INSERT INTO filmes.Site (Nome_Site, URL) VALUES
('IMDb', 'https://www.imdb.com'),
('Rotten Tomatoes', 'https://www.rottentomatoes.com'),
('Metacritic', 'https://www.metacritic.com'),
('Letterboxd', 'https://letterboxd.com'),
('FilmAffinity', 'https://www.filmaffinity.com'),
('The Movie Database (TMDb)', 'https://www.themoviedb.org');


INSERT INTO filmes.Premio (Nome_Premio, Descricao) VALUES 
('Oscar - Melhor Filme', 'Premiado ao melhor filme do ano.'),
('Oscar - Melhor Diretor', 'Premiado ao melhor diretor.'),
('Oscar - Melhor Edição de Som', 'Premiado ao filme com melhor edição de som.'),
('Oscar - Melhor Ator', 'Premiado ao melhor ator principal.'),
('Oscar - Melhor Filme Estrangeiro', 'Premiado ao melhor filme estrangeiro.'),
('Oscar - Melhor Atriz', 'Premiado à melhor atriz principal.'),
('Oscar - Melhor Maquiagem', 'Premiado ao filme com a melhor maquiagem.'),
('Oscar - Melhor Direção de Arte', 'Premiado ao filme com a melhor direção de arte.'),
('Oscar - Melhor Mixagem de Som', 'Premiado ao filme com a melhor mixagem de som.'),
('Oscar - Melhor Efeitos Visuais', 'Premiado ao filme com os melhores efeitos visuais.'),
('Oscar - Melhor Montagem', 'Premiado ao filme com melhor montagem.'),
('Oscar - Melhor Ator Coadjuvante', 'Premiado ao melhor ator coadjuvante.'),
('Oscar - Melhor Atriz Coadjuvante', 'Premiado à melhor atriz coadjuvante.'),
('Oscar - Melhor Roteiro Original', 'Premiado ao melhor roteiro original.'),
('Oscar - Melhor Roteiro Adaptado', 'Premiado ao melhor roteiro adaptado.'),
('Oscar - Melhor Animação', 'Premiado ao melhor filme de animação.'),
('Oscar - Melhor Filme Internacional', 'Premiado ao melhor filme internacional.'),
('Oscar - Melhor Fotografia', 'Premiado à melhor fotografia.'),
('Oscar - Melhor Edição', 'Premiado à melhor edição.'),
('Oscar - Melhor Trilha Sonora Original', 'Premiado à melhor trilha sonora original.'),
('Oscar - Melhor Canção Original', 'Premiado à melhor canção original.'),
('Oscar - Melhor Design de Produção', 'Premiado ao melhor design de produção.'),
('Oscar - Melhor Figurino', 'Premiado ao melhor figurino.'),
('Oscar - Melhor Maquiagem e Penteados', 'Premiado à melhor maquiagem e penteados.'),
('Oscar - Melhores Efeitos Visuais', 'Premiado aos melhores efeitos visuais.'),
('Oscar - Melhor Som', 'Premiado ao melhor som.'),
('Oscar - Melhor Documentário', 'Premiado ao melhor documentário.'),
('Globo de Ouro - Melhor Filme - Drama', 'Premiado ao melhor filme de drama.'),
('Globo de Ouro - Melhor Filme - Comédia ou Musical', 'Premiado ao melhor filme de comédia ou musical.'),
('Globo de Ouro - Melhor Diretor', 'Premiado ao melhor diretor.'),
('Globo de Ouro - Melhor Ator - Drama', 'Premiado ao melhor ator em drama.'),
('Globo de Ouro - Melhor Atriz - Drama', 'Premiado à melhor atriz em drama.'),
('Globo de Ouro - Melhor Ator - Comédia ou Musical', 'Premiado ao melhor ator em comédia ou musical.'),
('Globo de Ouro - Melhor Atriz - Comédia ou Musical', 'Premiado à melhor atriz em comédia ou musical.'),
('Globo de Ouro - Melhor Ator Coadjuvante', 'Premiado ao melhor ator coadjuvante.'),
('Globo de Ouro - Melhor Atriz Coadjuvante', 'Premiado à melhor atriz coadjuvante.'),
('Globo de Ouro - Melhor Roteiro', 'Premiado ao melhor roteiro.'),
('Globo de Ouro - Melhor Animação', 'Premiado ao melhor filme de animação.'),
('Globo de Ouro - Melhor Filme Estrangeiro', 'Premiado ao melhor filme estrangeiro.'),
('Globo de Ouro - Melhor Trilha Sonora Original', 'Premiado à melhor trilha sonora original.'),
('Globo de Ouro - Melhor Canção Original', 'Premiado à melhor canção original.'),
('Palma de Ouro', 'Premiado ao melhor filme do Festival de Cannes.'),
('Grande Prêmio do Júri', 'Premiado ao segundo melhor filme do Festival de Cannes.'),
('Prêmio do Júri', 'Premiado pelo júri do Festival de Cannes.'),
('Melhor Diretor - Cannes', 'Premiado ao melhor diretor no Festival de Cannes.'),
('Melhor Ator - Cannes', 'Premiado ao melhor ator no Festival de Cannes.'),
('Melhor Atriz - Cannes', 'Premiado à melhor atriz no Festival de Cannes.'),
('Melhor Roteiro - Cannes', 'Premiado ao melhor roteiro no Festival de Cannes.'),
('Prêmio de Curta-Metragem - Cannes', 'Premiado ao melhor curta-metragem no Festival de Cannes.'),
('Câmera de Ouro', 'Premiado ao melhor primeiro filme no Festival de Cannes.'),
('Prêmio do Júri Ecumênico', 'Premiado pelo júri ecumênico no Festival de Cannes.'),
('Palma Queer', 'Premiado ao melhor filme de temática LGBTQ+ no Festival de Cannes.'), 
('Urso de Ouro', 'Premiado ao melhor filme do Festival de Berlim.'),
('Urso de Prata - Grande Prêmio do Júri', 'Premiado ao segundo melhor filme do Festival de Berlim.'),
('Urso de Prata - Melhor Diretor', 'Premiado ao melhor diretor no Festival de Berlim.'),
('Urso de Prata - Melhor Ator', 'Premiado ao melhor ator no Festival de Berlim.'),
('Urso de Prata - Melhor Atriz', 'Premiado à melhor atriz no Festival de Berlim.'),
('Urso de Prata - Melhor Roteiro', 'Premiado ao melhor roteiro no Festival de Berlim.'),
('Urso de Prata - Contribuição Artística Excepcional', 'Premiado por contribuição artística excepcional no Festival de Berlim.'),
('BAFTA - Melhor Filme', 'Premiado ao melhor filme no BAFTA.'),
('BAFTA - Melhor Diretor', 'Premiado ao melhor diretor no BAFTA.'),
('BAFTA - Melhor Ator', 'Premiado ao melhor ator no BAFTA.'),
('BAFTA - Melhor Atriz', 'Premiado à melhor atriz no BAFTA.'),
('BAFTA - Melhor Ator Coadjuvante', 'Premiado ao melhor ator coadjuvante no BAFTA.'),
('BAFTA - Melhor Atriz Coadjuvante', 'Premiado à melhor atriz coadjuvante no BAFTA.'),
('BAFTA - Melhor Filme Britânico', 'Premiado ao melhor filme britânico no BAFTA.'),
('BAFTA - Melhor Filme de Animação', 'Premiado ao melhor filme de animação no BAFTA.'),
('BAFTA - Melhor Filme Estrangeiro', 'Premiado ao melhor filme estrangeiro no BAFTA.'),
('BAFTA - Melhor Roteiro Original', 'Premiado ao melhor roteiro original no BAFTA.'),
('BAFTA - Melhor Roteiro Adaptado', 'Premiado ao melhor roteiro adaptado no BAFTA.'),
('BAFTA - Melhor Fotografia', 'Premiado à melhor fotografia no BAFTA.'),
('BAFTA - Melhor Edição', 'Premiado à melhor edição no BAFTA.'),
('BAFTA - Melhor Design de Produção', 'Premiado ao melhor design de produção no BAFTA.'),
('BAFTA - Melhor Figurino', 'Premiado ao melhor figurino no BAFTA.'),
('BAFTA - Melhor Maquiagem e Penteados', 'Premiado à melhor maquiagem e penteados no BAFTA.'),
('BAFTA - Melhor Som', 'Premiado ao melhor som no BAFTA.'),
('BAFTA - Melhores Efeitos Visuais', 'Premiado aos melhores efeitos visuais no BAFTA.'),
('BAFTA - Melhor Trilha Sonora Original', 'Premiado à melhor trilha sonora original no BAFTA.'),
('BAFTA - Melhor Curta-Metragem Britânico', 'Premiado ao melhor curta-metragem britânico no BAFTA.'),
('BAFTA - Melhor Curta-Metragem de Animação Britânico', 'Premiado ao melhor curta-metragem de animação britânico no BAFTA.'),
('César - Melhor Filme', 'Premiado ao melhor filme no César.'),
('César - Melhor Diretor', 'Premiado ao melhor diretor no César.'),
('César - Melhor Ator', 'Premiado ao melhor ator no César.'),
('César - Melhor Atriz', 'Premiado à melhor atriz no César.'),
('César - Melhor Ator Coadjuvante', 'Premiado ao melhor ator coadjuvante no César.'),
('César - Melhor Atriz Coadjuvante', 'Premiado à melhor atriz coadjuvante no César.'),
('César - Melhor Filme Estrangeiro', 'Premiado ao melhor filme estrangeiro no César.'),
('César - Melhor Roteiro Original', 'Premiado ao melhor roteiro original no César.'),
('César - Melhor Roteiro Adaptado', 'Premiado ao melhor roteiro adaptado no César.'),
('César - Melhor Fotografia', 'Premiado à melhor fotografia no César.'),
('César - Melhor Edição', 'Premiado à melhor edição no César.'),
('César - Melhor Design de Produção', 'Premiado ao melhor design de produção no César.'),
('César - Melhor Figurino', 'Premiado ao melhor figurino no César.'),
('César - Melhor Maquiagem', 'Premiado à melhor maquiagem no César.'),
('César - Melhor Som', 'Premiado ao melhor som no César.'),
('César - Melhores Efeitos Visuais', 'Premiado aos melhores efeitos visuais no César.'),
('César - Melhor Trilha Sonora Original', 'Premiado à melhor trilha sonora original no César.'),
('Leão de Ouro', 'Premiado ao melhor filme do Festival de Veneza.'),
('Leão de Prata - Grande Prêmio do Júri', 'Premiado ao segundo melhor filme do Festival de Veneza.'),
('Leão de Prata - Melhor Diretor', 'Premiado ao melhor diretor no Festival de Veneza.'),
('Copa Volpi - Melhor Ator', 'Premiado ao melhor ator no Festival de Veneza.'),
('Copa Volpi - Melhor Atriz', 'Premiado à melhor atriz no Festival de Veneza.'),
('Prêmio Especial do Júri', 'Premiado pelo júri do Festival de Veneza.'),
('Prêmio Marcello Mastroianni', 'Premiado ao melhor ator ou atriz jovem no Festival de Veneza.'),
('Prêmio de Roteiro - Veneza', 'Premiado ao melhor roteiro no Festival de Veneza.'),
('Prêmio Orizzonti', 'Premiado por reconhecer filmes em categorias específicas no Festival de Veneza.');